name: iOS Build

on:
  workflow_dispatch:  # 수동 실행
    inputs:
      build_type:
        description: '빌드 타입'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      deploy_testflight:
        description: 'TestFlight 배포'
        required: false
        default: false
        type: boolean

  # push 시 자동 빌드는 주석 처리 (필요시 활성화)
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'apps/app/**'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build web app
      working-directory: apps/app
      run: |
        pnpm install
        pnpm build

    - name: Check build output
      working-directory: apps/app
      run: |
        echo "Checking build directory..."
        ls -la build/ || echo "Build directory not found"

    - name: Create www symlink
      working-directory: apps/app
      run: |
        if [ -d "build" ]; then
          ln -sf build www
          echo "Created symlink: www -> build"
        else
          echo "Error: build directory not found!"
          exit 1
        fi

    - name: Check if iOS platform exists
      working-directory: apps/app
      run: |
        if [ ! -d "ios" ]; then
          echo "iOS platform not found, adding..."
          npx cap add ios
        else
          echo "iOS platform already exists"
        fi

    - name: Sync iOS platform
      working-directory: apps/app
      run: |
        npx cap sync ios || echo "Sync completed with warnings"

    - name: Fix iOS public directory
      working-directory: apps/app
      run: |
        echo "Fixing iOS public directory..."
        # Remove symlink if exists
        if [ -L "ios/App/App/public" ]; then
          echo "Removing public symlink..."
          rm ios/App/App/public
        fi

        # Copy actual files
        if [ ! -d "ios/App/App/public" ]; then
          echo "Creating public directory with actual files..."
          cp -r build ios/App/App/public || cp -r www ios/App/App/public || echo "Using empty public"
          mkdir -p ios/App/App/public
        fi

        echo "Public directory fixed"
        ls -la ios/App/App/

    - name: Create config.xml if missing
      working-directory: apps/app/ios/App/App
      run: |
        if [ ! -f "config.xml" ]; then
          echo "Creating config.xml..."
          echo '<?xml version="1.0" encoding="UTF-8"?>' > config.xml
          echo '<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">' >> config.xml
          echo '  <access origin="*" />' >> config.xml
          echo '  <content src="index.html" />' >> config.xml
          echo '  <name>NanumPay</name>' >> config.xml
          echo '</widget>' >> config.xml
          echo "config.xml created"
        else
          echo "config.xml already exists"
        fi

    - name: Install CocoaPods dependencies
      working-directory: apps/app/ios/App
      run: |
        pod install || pod install --repo-update

    - name: List Xcode schemes
      working-directory: apps/app/ios/App
      run: |
        xcodebuild -list -workspace App.xcworkspace

    - name: Build iOS app
      working-directory: apps/app/ios/App
      run: |
        # Ensure public exists as real directory
        if [ -L "App/public" ]; then
          rm App/public
          mkdir -p App/public
        fi

        xcodebuild clean build \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -sdk iphonesimulator \
          -derivedDataPath build \
          -arch x86_64 \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          EXCLUDED_SOURCE_FILE_NAMES="public/*"

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: apps/app/ios/App/build/Build/Products/Debug-iphonesimulator/

    - name: Comment on PR (if PR)
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ iOS 빌드가 성공적으로 완료되었습니다!'
          })